### ISSUE TITLE
'kLSSharedFileListSessionLoginItems' was deprecated in OS X 10.11: Use a LaunchAgent, XPCService or the ServiceManagement APIs instead.

### ISSUE THREAD

**Issue by miniLV** [Clipy/LoginServiceKit#10]
The following warning is run in swift5: 'kLSSharedFileListSessionLoginItems' was deprecated in OS X 10.11: Use a LaunchAgent, XPCService or the ServiceManagement APIs instead.

**Comment by Econa77** [comment]
@miniLV Sorry for late reply.
The only way to add a macOS login item that is not currently deprecated is to create a helper application using ServiceManagementFramework API or add it using AppleScript 😢 
To use AppleScript, need to get SystemEvent permission and it is not suitable for adding to login items.
And Creating helper applications has a very different approach and is not suitable for support in this library.

For this reason, support for this library itself will end when the use of the API is terminated.

ref: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLoginItems.html#//apple_ref/doc/uid/10000172i-SW5-SW5
