### ISSUE TITLE
If you open "sandbox", it will not work

### ISSUE THREAD

**Issue by Zss1990** [Clipy/LoginServiceKit#37]
If you open "sandbox", it will not work;
But the App Store must ask for "sandbox."
Please help me

**Comment by Econa77** [comment]
This library cannot be used in a Sandbox environment. If you wish to achieve similar functionality in a Sandbox environment, we recommend creating a Helper application. Please refer to the following article for more information.

https://hoishing.medium.com/adding-login-items-for-macos-7d76458f6495
